name: Provision Infrastructure

on:
  push:
    branches:
      - "main" 
    paths:
      - "Infrastructure/**"
      - ".github/workflows/bicep.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  provision-service-bus:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Empty Out Environment
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        scope: resourcegroup
        template: ./Infrastructure/empty.bicep
        failOnStdErr: false
        deploymentName: empty-bicep-ci
        deploymentMode: Complete

    - name: Provision Resources
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        scope: resourcegroup
        template: ./Infrastructure/main.bicep
        parameters: serviceBusNamespaceName=${{ vars.RESOURCE_NAME }}sb storageAccountName=${{ vars.RESOURCE_NAME }}sa appServicePlanName=${{ vars.RESOURCE_NAME }}asp functionAppName=${{ vars.RESOURCE_NAME }}func webAppName=${{ vars.RESOURCE_NAME }}web
        failOnStdErr: false
        deploymentName: bicep-ci
        deploymentMode: Complete
