name: Build and deploy web and function apps
      
on:
  push:
    branches:
      - "main" 
    paths:
      - "ServiceBus/**"
      - ".github/workflows/web.yml"
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './Code/PeopleFunction'
  AZURE_WEBAPP_PACKAGE_PATH: './Code/PeopleWeb'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Set up DotNet 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Set up DotNet 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: 'Build Function Project'
        shell: bash
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./functionoutput
          popd

      - name: 'Build Web Project'
        shell: bash
        run: |
          pushd '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release
          dotnet publish -c Release -o ./weboutput
          popd

      - name: 'Deploy Function App'
        uses: Azure/functions-action@v1
        with:
          app-name: '${{ vars.RESOURCE_NAME }}func'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/functionoutput'

      - name: Deploy Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: '${{ vars.RESOURCE_NAME }}web'
          slot-name: 'Production'
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/weboutput'
