name: Static Web Apps Build and Deploy

description: "Build and deploy Function App"
inputs:
  AZURE_TENANT_ID:
    required: true
  AZURE_SUBSCRIPTION_ID:
    required: true
  AZURE_CLIENT_ID:
    required: true

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:

      # Log into Azure
    - name: Login via Azure
      uses: azure/login@v1
      with:
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
    
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Get SWA Tokens
      id: swatoken
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: echo SWA_TOKEN=$(az staticwebapp secrets list --name ${{ vars.RESOURCE_NAME }} --query 'properties.apiKey') | tr -d '"' >> "$GITHUB_OUTPUT"

    # - name: Build And Deploy
    #   id: builddeploy
    #   uses: Azure/static-web-apps-deploy@v1
    #   with:
    #     azure_static_web_apps_api_token: ${{ steps.swatoken.outputs.SWA_TOKEN }}
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     action: "upload"
    #     app_location: "SWAClient"
    #     api_location: ""
    #     output_location: "wwwroot"

    # - name: Reset SWA Token
    #   uses: azure/CLI@v1
    #   with:
    #     azcliversion: latest
    #     inlineScript: az staticwebapp secrets reset-api-key --name ${{ vars.RESOURCE_NAME }}swa --resource-group ${{ vars.RESOURCE_NAME }} --no-wait
