name: Function App Build and Deploy 
      
on:
  push:
    branches:
      - "main" 
    paths:
      - ".github/workflows/function.yml"
      - ".github/workflows/function/action.yml"
      - "PartyTriviaAPI/**"
      - "PartyTriviaShared/**"
  workflow_dispatch:
    
jobs:
  build-and-deploy:
    uses: ./.github/workflows/functionBuildAndDeploy.yml
