name: Function App Build and Deploy 
      
on:
  push:
    branches:
      - "main" 
    paths:
      - ".github/workflows/function.yml"
      - ".github/workflows/function/action.yml"
      - "PartyTriviaAPI/**"
      - "PartyTriviaShared/**"
  workflow_dispatch:
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Deploy Web
      uses: ./.github/workflows/functionBuildAndDeploy.yml
