name: Function App CI
      
on:
  push:
    branches:
      - "main" 
    paths:
      - ".github/workflows/function.yml"
      - ".github/workflows/function/action.yml"
      - "PartyTriviaAPI/**"
      - "PartyTriviaShared/**"
  workflow_dispatch:
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy Function
      uses: ./.github/workflows/function
      with:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        RESOURCE_NAME: ${{ vars.RESOURCE_NAME }}
