name: Provision Infrastructure

on:
  push:
    branches:
      - "main" 
    paths:
      - ".github/workflows/iac.yml"
      - "IaC/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  provision-azure-resources:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}

    - name: Empty Out Environment
      uses: azure/CLI@v1
      continue-on-error: true
      with:
        azcliversion: 2.30.0
        inlineScript: az group delete --name ${{ vars.RESOURCE_NAME }} --yes

    - name: Provision Resources
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        scope: subscription
        region: centralus
        template: ./IaC/main.bicep
        parameters: location=centralus commonResourceName=${{ vars.RESOURCE_NAME }}
        failOnStdErr: false
        deploymentName: bicep-ci-${{ github.run_id }}

  call-workflow-functions:
    uses: ./.github/workflows/function.yml
    needs: provision-azure-resources
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

  call-workflow-web:
    uses: ./.github/workflows/web.yml
    needs: provision-azure-resources
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
