name: Provision Infrastructure

on:
  push:
    branches:
      - "main" 
    paths:
      - ".github/workflows/iac.yml"
      - "IaC/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  cleanup-resources:
    runs-on: ubuntu-latest
    environment: CleanupResources
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Remove www Cloudflare DNS
      env:
        APIKey: ${{ secrets.CLOUDFLARE_APIKEY }}
        ZoneId: ${{ secrets.CLOUDFLARE_ZONEID }}
      run: ./IaC/dnsDelete.ps1
      shell: pwsh

    - name: Log into Azure
      uses: azure/login@v1
      with:
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}

    - name: Empty Out Azure Environment
      uses: azure/CLI@v1
      continue-on-error: true
      with:
        azcliversion: 2.48.1
        inlineScript: az group delete --name ${{ vars.RESOURCE_NAME }} --yes
  
  provision-azure-resources:
    runs-on: ubuntu-latest
    environment: IaCDeloy
    needs: cleanup-resources
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}

    - name: Provision Resources
      uses: azure/arm-deploy@v1
      id: deploy
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        scope: subscription
        region: centralus
        template: ./IaC/main.bicep
        parameters: location=centralus commonResourceName=${{ vars.RESOURCE_NAME }}
        failOnStdErr: false
        deploymentName: bicep-ci-${{ github.run_id }}

    - name: Get SWA Default Hostname
      id: swahostname
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: echo DEFAULT_HOSTNAME=$(az staticwebapp show -n ${{ vars.RESOURCE_NAME }} --query 'defaultHostname') | tr -d '"' >> "$GITHUB_OUTPUT" 

    - name: Validate Hostname
      run: echo ${{ steps.swahostname.outputs.DEFAULT_HOSTNAME }}

    - name: Set Cloudflare DNS
      env:
        APIKey: ${{ secrets.CLOUDFLARE_APIKEY }}
        ZoneId: ${{ secrets.CLOUDFLARE_ZONEID }}
        HostName: ${{ steps.swahostname.outputs.DEFAULT_HOSTNAME }}
      run: ./IaC/dnsCreate.ps1
      shell: pwsh

  call-deploy-app-workflows:
    runs-on: ubuntu-latest
    environment: AppDeploy
    needs: provision-azure-resources
    steps:

    - name: Deploy Functions
      uses: ./.github/workflows/function.yml
      with:
        secrets: inherit

    - name: Deploy Web App
      uses: ./.github/workflows/web.yml
      with:
        secrets: inherit

  resolve-dns:
    runs-on: ubuntu-latest
    environment: ResolveDNS
    needs: call-deploy-app-workflows
    steps:
      
    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}

    - name: Provision Resources
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        scope: subscription
        region: centralus
        template: ./IaC/dns.bicep
        parameters: commonResourceName=${{ vars.RESOURCE_NAME }}
        failOnStdErr: false
        deploymentName: bicep-dns-ci-${{ github.run_id }}
