name: Web App CI

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/web.yml"
      - ".github/workflows/web/action.yml"
      - "PartyTriviaWeb/**"
      - "PartyTriviaShared/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Deploy Web App
      uses: ./.github/workflows/web
      with:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        RESOURCE_NAME: ${{ vars.RESOURCE_NAME }}
