name: Static Web Apps Build and Deploy

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/web.yml"
      - ".github/workflows/web/action.yml"
      - "PartyTriviaWeb/**"
      - "PartyTriviaShared/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Deploy Web
      uses: ./.github/workflows/web
      with:
        secrets: inherit
